### ISSUE TITLE
JSON not adding whitelisted site

### ISSUE THREAD

**Issue by MlooneyHV** [Landsil/apps_script--GoogleWorkspace-API#1]
Created uBlock Template, added website and Generated the JSON.

I added the JSON to the "Policy for extension" area in Google Admin for uBlock but it is **_not_** whitelisting the website.

**Comment by Landsil** [comment]
Have you restarted chrome / ublock? It won't pickup up new policy without it.

You can see if policy was added here: chrome://policy/

**Comment by MlooneyHV** [comment]
In chrome://policy/ it shows that it picked it up but when navigating to the website it still shows a number count of items being blocked.

EDIT: Chrome/UBlock were also restarted

**Comment by Landsil** [comment]
In that case it works correctly.

Please check what actually shows inside of uBlock allowed list and what's their formatting structure.
